### ISSUE TITLE
View in widget 8 lässt editor abstürzen in vis2

### ISSUE THREAD

**Issue by Knobi83** [ioBroker/ioBroker.vis-2#122]
Das Problem besteht weiterhin. Siehe auch" https://github.com/ioBroker/ioBroker.vis-2/issues/49" 

Bei Änderungen im Widget View in 8 stürzt die VIS-2 ab und lädt sich auch nicht neu.  In der VIS-2 werden die Änderungen nicht übernommen und gespeichert. Der Bildschirm bleibt schwarz. 
Es wurde ein Projekt von VIS auf VIS-2 übernommen. 

```
bootstrap.jsx:16 iobroker.vis-2@2.3.2 using theme "blue"
Prompt.js:14
██╗ ██████╗ ██████╗ ██████╗ ██████╗ ██╗ ██╗███████╗██████╗
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║ ██║██████╔╝██████╔╝██║ ██║█████╔╝ █████╗ ██████╔╝
██║██║ ██║██╔══██╗██╔══██╗██║ ██║██╔═██╗ ██╔══╝ ██╔══██╗
██║╚██████╔╝██████╔╝██║ ██║╚██████╔╝██║ ██╗███████╗██║ ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝ ╚═╝ ╚═════╝ ╚═╝ ╚═╝╚══════╝╚═╝ ╚═╝

Prompt.js:15 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:16 Help us to create open source project with reactJS!
Prompt.js:17 See you :)
instrument.ts:144 Translate: background
instrument.ts:144 Version vis-jqui-mfd: 1.0.12
instrument.ts:144 Version Info-Adapter-Widget: 1.9.26
instrument.ts:144 Version players: 0.1.0
instrument.ts:144 Version iobroker.vis-keyboard: 0.0.2
instrument.ts:144 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
instrument.ts:144 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
instrument.ts:144 Version vis-materialdesign: 0.5.94
instrument.ts:144 vis-materialdesign: vibration supported by device: 'true'
instrument.ts:144 Translate: hqwidgets
instrument.ts:144 Translate: info
instrument.ts:144 Translate: jqplot
instrument.ts:144 Translate: jqui-mfd
instrument.ts:144 Translate: keyboard
instrument.ts:144 Translate: materialdesign
instrument.ts:144 Translate: players
instrument.ts:144 Translate: spotify-premium
instrument.ts:144 Translate: swipe
instrument.ts:144 vis-materialdesign: click audio file '/vis.0/materialdesign-widgets-click-sound.mp3' not exists!
(anonymous) @ instrument.ts:144
instrument.ts:144 sentry initialized for vis-materialdesign
instrument.ts:144 [2023-10-31T10:48:18.233Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.Kamera.Bild_in_VIS_Eingang
instrument.ts:144 [2023-10-31T10:48:18.236Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.Kamera.Bild_in_VIS_Garage
instrument.ts:144 [2023-10-31T10:48:18.240Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.VIS.Material_Design_Master_für_Visualisierung.Erdgeschoss
instrument.ts:144 vis-materialdesign: theme default 'colors' (light) successfully bound to css variables
instrument.ts:144 vis-materialdesign: theme 'colors' (light) successfully bound to css variables
instrument.ts:144 vis-materialdesign: theme default 'fonts' successfully bound to css variables
instrument.ts:144 vis-materialdesign: theme 'fonts' successfully bound to css variables
instrument.ts:144 vis-materialdesign: theme default 'font-sizes' successfully bound to css variables
instrument.ts:144 vis-materialdesign: theme 'font-sizes' successfully bound to css variables
instrument.ts:144 [2023-10-31T10:48:21.826Z] -UNSUBSCRIBE: 0_userdata.0.Datenpunkte.Kamera.Bild_in_VIS_Eingang
instrument.ts:144 [2023-10-31T10:48:21.827Z] -UNSUBSCRIBE: 0_userdata.0.Datenpunkte.Kamera.Bild_in_VIS_Garage
instrument.ts:144 [2023-10-31T10:48:21.828Z] -UNSUBSCRIBE: 0_userdata.0.Datenpunkte.VIS.Material_Design_Master_für_Visualisierung.Erdgeschoss
instrument.ts:144 [2023-10-31T10:48:21.885Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.VIS.Material_Design_Master_für_Visualisierung.Erdgeschoss
instrument.ts:144 [2023-10-31T10:48:21.933Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.VIS.Nachrichtenanzeige.Anzeige_einblenden_ausblenden
instrument.ts:144 [2023-10-31T10:48:21.940Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.VIS.Nachrichtenanzeige.Nachrichtenanzeige
instrument.ts:144 [2023-10-31T10:48:21.946Z] +SUBSCRIBE: smart-eq.0.W1A4530911Y255884.precond.data.chargingstatus.value
instrument.ts:144 [2023-10-31T10:48:21.953Z] +SUBSCRIBE: fullybrowser.0.192_168_178_41.Commands.startApplication
instrument.ts:144 [2023-10-31T10:48:21.957Z] +SUBSCRIBE: sonoff.0.Steckdose Trockner.ENERGY_Power
instrument.ts:144 [2023-10-31T10:48:21.960Z] +SUBSCRIBE: shelly.0.shellyplus1pm#441793d00828#1.Relay0.Power
instrument.ts:144 [2023-10-31T10:48:21.966Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.VIS.Überwachung.Shelly_Überwachung_VIS_Darstellung_Rot
instrument.ts:144 [2023-10-31T10:48:21.969Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.Briefkasten.Vis_anzeige
instrument.ts:144 [2023-10-31T10:48:21.972Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.Türen_und_Fenster.Abfrage_Fenster_offen_und_Darstellung_VIS_Rot
instrument.ts:144 [2023-10-31T10:48:21.973Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.Türen_und_Fenster.Abfrage_Türen_offen_und_Darstellung_VIS_Rot
instrument.ts:144 [2023-10-31T10:48:21.975Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.VIS.Überwachung.Geräteüberwachung_VIS_Darstellung
instrument.ts:144 [2023-10-31T10:48:21.978Z] +SUBSCRIBE: bring.0.35fc8225-b02f-4503-9508-b422f0166407.count
instrument.ts:144 [2023-10-31T10:48:21.982Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.VIS.Überwachung.Batterien
instrument.ts:144 [2023-10-31T10:48:21.982Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.VIS.Überwachung.Batterien_Darstellung_Rot_VIS
instrument.ts:144 [2023-10-31T10:48:21.984Z] +SUBSCRIBE: bring.0.046f7050-efe4-4708-aa05-6038713361be.count
instrument.ts:144 [2023-10-31T10:48:21.986Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.VIS.Pflanzen.Darstellung_VIS_Rot
instrument.ts:144 [2023-10-31T10:48:21.988Z] +SUBSCRIBE: javascript.0.variables.dayTime
instrument.ts:144 [2023-10-31T10:48:21.990Z] +SUBSCRIBE: alexa-timer-vis.0.timer1.name
instrument.ts:144 [2023-10-31T10:48:21.990Z] +SUBSCRIBE: alexa-timer-vis.0.timer1.alive
instrument.ts:144 [2023-10-31T10:48:21.992Z] +SUBSCRIBE: tr-064.0.states.wlanGuest
instrument.ts:144 [2023-10-31T10:48:21.993Z] +SUBSCRIBE: alexa-timer-vis.0.timer1.percent
instrument.ts:144 [2023-10-31T10:48:21.999Z] +SUBSCRIBE: alexa-timer-vis.0.timer1.string
instrument.ts:144 [2023-10-31T10:48:22.002Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.Heizung.Status_Heizungen_Standby
instrument.ts:144 [2023-10-31T10:48:22.004Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.Heizung.Status_Heizung_aktiv
instrument.ts:144 [2023-10-31T10:48:22.006Z] +SUBSCRIBE: 0_userdata.0.Datenpunkte.Routinen.Freitext
instrument.ts:144 [2023-10-31T10:48:22.009Z] +SUBSCRIBE: homeconnect.0.SIEMENS-HM876G2B6-68A40E6E02BA.programs.active.options.BSH_Common_Option_ProgramProgress
instrument.ts:144 [2023-10-31T10:48:22.012Z] +SUBSCRIBE: homeconnect.0.011110386957004615.programs.active.options.BSH_Common_Option_ProgramProgress
instrument.ts:144 [2023-10-31T10:48:22.015Z] +SUBSCRIBE: homeconnect.0.SIEMENS-HM876G2B6-68A40E6E02BA.status.BSH_Common_Status_OperationState
instrument.ts:144 [2023-10-31T10:48:22.018Z] +SUBSCRIBE: alexa-timer-vis.0.timer1.Reset
instrument.ts:144 [2023-10-31T10:48:22.021Z] +SUBSCRIBE: alexa-timer-vis.0.timer2.name
instrument.ts:144 [2023-10-31T10:48:22.021Z] +SUBSCRIBE: alexa-timer-vis.0.timer2.alive
instrument.ts:144 [2023-10-31T10:48:22.023Z] +SUBSCRIBE: alexa-timer-vis.0.timer2.percent
instrument.ts:144 [2023-10-31T10:48:22.024Z] +SUBSCRIBE: alexa-timer-vis.0.timer2.string
instrument.ts:144 [2023-10-31T10:48:22.026Z] +SUBSCRIBE: alexa-timer-vis.0.timer2.Reset
instrument.ts:144 [2023-10-31T10:48:22.033Z] +SUBSCRIBE: alexa-timer-vis.0.timer3.name
instrument.ts:144 [2023-10-31T10:48:22.033Z] +SUBSCRIBE: alexa-timer-vis.0.timer3.alive
instrument.ts:144 [2023-10-31T10:48:22.037Z] +SUBSCRIBE: alexa-timer-vis.0.timer3.percent
instrument.ts:144 [2023-10-31T10:48:22.039Z] +SUBSCRIBE: alexa-timer-vis.0.timer3.string
instrument.ts:144 [2023-10-31T10:48:22.040Z] +SUBSCRIBE: alexa-timer-vis.0.timer3.Reset
instrument.ts:144 Translate: show code
instrument.ts:144 Translate: all
instrument.ts:144 Translate: w00001
instrument.ts:144 Translate: w00513
instrument.ts:144 Translate: w001136
instrument.ts:144 [1698749355438 / w001136] Rerender because of data.contains_view_0: null !== 00_Übersicht
instrument.ts:144 widget updated
instrument.ts:144 TypeError: Cannot set properties of undefined (setting '00_Übersicht')
at i.value (visView.jsx:1349:57)
at ji (react-dom.production.min.js:204:189)
at Li (react-dom.production.min.js:203:149)
at Cs (react-dom.production.min.js:292:172)
at Hl (react-dom.production.min.js:280:389)
at gl (react-dom.production.min.js:280:320)
at zl (react-dom.production.min.js:280:180)
at al (react-dom.production.min.js:271:88)
at ol (react-dom.production.min.js:268:429)
at V (scheduler.production.min.js:13:203)
at MessagePort.T (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:144
(anonymous) @ instrument.ts:129
(anonymous) @ captureconsole.ts:73
di @ react-dom.production.min.js:189
n.callback @ react-dom.production.min.js:189
Do @ react-dom.production.min.js:144
xs @ react-dom.production.min.js:262
Hs @ react-dom.production.min.js:260
Ms @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Vl @ react-dom.production.min.js:281
ol @ react-dom.production.min.js:270
V @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
react-dom.production.min.js:283 Uncaught TypeError: Cannot set properties of undefined (setting '00_Übersicht')
at i.value (visView.jsx:1349:57)
at ji (react-dom.production.min.js:204:189)
at Li (react-dom.production.min.js:203:149)
at Cs (react-dom.production.min.js:292:172)
at Hl (react-dom.production.min.js:280:389)
at gl (react-dom.production.min.js:280:320)
at zl (react-dom.production.min.js:280:180)
at al (react-dom.production.min.js:271:88)
at ol (react-dom.production.min.js:268:429)
at V (scheduler.production.min.js:13:203)
at MessagePort.T (scheduler.production.min.js:14:128)
value @ visView.jsx:1349
ji @ react-dom.production.min.js:204
Li @ react-dom.production.min.js:203
Cs @ react-dom.production.min.js:292
Hl @ react-dom.production.min.js:280
gl @ react-dom.production.min.js:280
zl @ react-dom.production.min.js:280
al @ react-dom.production.min.js:271
ol @ react-dom.production.min.js:268
V @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
```

**Comment by foxriver76** [comment]
Bitte mit 2.3.4 testen, zumindest kann ich es nicht nachstellen, ansonsten bitte so genau wie möglich sagen wie das zu reproduzieren ist.

**Comment by Feuer-sturm** [comment]
@Knobi83 Ich hatte es bei einem Import von vis nach vis2 schon einmal das sich die importieren widgets anders verhalten haben als wenn ich das widget neu in den vis2 editor gezogen hab.
Lösche ansonsten mal dein Widget View in 8 in deinem editor und füge es noch einmal neu hinzu und konfiguriere es neu.
