### ISSUE TITLE
[bug] after update to 2.9.21 there is a black screen in JAEGER-Design

### ISSUE THREAD

**Issue by obodeldog** [ioBroker/ioBroker.vis-2#327]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

after update to 2.9.21 there is a black screen in JAEGER-Design

### To Reproduce

after update to 2.9.21 there is a black screen in JAEGER-Design

### Expected behavior

no blackscreen. 

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/35403739/ab517fd7-0798-4402-8b97-b84fcb5b97da)

### Adapter version

2.9.21

### js-controller version

5.0.16

### Node version

v18.19.0

### Operating system

debian

**Comment by Feuer-sturm** [comment]
Bei mir kommt folgende Fehler in der Konsole, wenn ich mein Jaeger-Design Projekt öffnen möchte
Jaeger-Design v1.1.10
vis-2 version: 2.9.21


```
Layout-Darstellung wurde erzwungen, bevor die Seite vollständig geladen war. Falls Stylesheet noch nicht geladen sind, kann dies zu einem kurzzeitigen Darstellung des Inhalts ohne Formatierung führen. edit.html
iobroker.vis-2@2.9.21 using theme "colored" bootstrap.jsx:16:8

██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
Prompt.js:15:12
Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters Prompt.js:16:12
Help us to create open source project with reactJS! Prompt.js:17:12
See you :) Prompt.js:18:12
[2024-01-21T20:40:26.924Z] Try to connect socket.io.js:66:41
Version vis-google-fonts: 0.0.1 console.ts:40:19
Version vis-history: 1.0.0 console.ts:40:19
Version vis-jqui-mfd: 1.0.12 console.ts:40:19
Version vis-map: 1.0.3 console.ts:40:19
Metro version: "1.2.0" console.ts:40:19
Version justgage: 2.1.0 console.ts:40:19
Version trashschedule: 3.1.3 console.ts:40:19
Version Info-Adapter-Widget: 1.9.26 console.ts:40:19
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools console.ts:40:19
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html console.ts:40:19
Version vis-materialdesign: 0.5.9 console.ts:40:19
common.visWidgets.i18n is deprecated. Use common.visWidgets.scheduler.i18n instead. console.ts:40:19
Uncaught (in promise) TypeError: t.update is not a function
    captureSession baseclient.ts:160
    _sendSessionUpdate hub.ts:661
    endSession hub.ts:598
    startSession hub.ts:630
    init sdk.ts:199
    init sdk.ts:94
    _initializeSentry widgets.min.js:1
    initializeSentry widgets.min.js:1
baseclient.ts:160:14
Translate: Write state console.ts:40:19
Translate: dwd console.ts:40:19
Translate: fancyswitch console.ts:40:19
Translate: history console.ts:40:19
Translate: jqplot console.ts:40:19
Translate: jqui-mfd console.ts:40:19
Translate: justgage console.ts:40:19
Translate: map console.ts:40:19
Translate: materialdesign console.ts:40:19
Translate: metro console.ts:40:19
Translate: spotify-premium console.ts:40:19
Translate: swipe console.ts:40:19
Translate: timeandweather console.ts:40:19
Translate: trashschedule console.ts:40:19
TypeError: o[e] is undefined
    d visUtils.jsx:284
    c visRxWidget.tsx:173
    d src_JaegerButton_jsx-src_JaegerDialog_jsx-src_JaegerSettings_jsx-src_icons_MenuIcon_jsx-src_i-efc534.a08e0e6f.chunk.js:1
    m src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_defi-8e4ea1.c6765f15.chunk.js:1
    React 8
    V scheduler.production.min.js:13
    T scheduler.production.min.js:14
console.ts:40:19
TypeError: o[e] is undefined
    d visUtils.jsx:284
    c visRxWidget.tsx:173
    d src_JaegerButton_jsx-src_JaegerDialog_jsx-src_JaegerSettings_jsx-src_icons_MenuIcon_jsx-src_i-efc534.a08e0e6f.chunk.js:1
    m src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_defi-8e4ea1.c6765f15.chunk.js:1
    React 8
    V scheduler.production.min.js:13
    T scheduler.production.min.js:14
console.ts:40:19
TypeError: o[e] is undefined
    d visUtils.jsx:284
    c visRxWidget.tsx:173
    d src_JaegerButton_jsx-src_JaegerDialog_jsx-src_JaegerSettings_jsx-src_icons_MenuIcon_jsx-src_i-efc534.a08e0e6f.chunk.js:1
    m src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_defi-8e4ea1.c6765f15.chunk.js:1
    React 8
    V scheduler.production.min.js:13
    T scheduler.production.min.js:14
console.ts:40:19
Uncaught TypeError: o[e] is undefined
    d visUtils.jsx:284
    c visRxWidget.tsx:173
    d src_JaegerButton_jsx-src_JaegerDialog_jsx-src_JaegerSettings_jsx-src_icons_MenuIcon_jsx-src_i-efc534.a08e0e6f.chunk.js:1
    m src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_defi-8e4ea1.c6765f15.chunk.js:1
    React 8
    V scheduler.production.min.js:13
    T scheduler.production.min.js:14
visUtils.jsx:284:19
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.54:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerButton_jsx-src_JaegerDialog_jsx-src_JaegerSettings_jsx-src_icons_MenuIcon_jsx-src_i-efc534.a08e0e6f.chunk.js
Source-Map-Adresse: src_JaegerButton_jsx-src_JaegerDialog_jsx-src_JaegerSettings_jsx-src_icons_MenuIcon_jsx-src_i-efc534.a08e0e6f.chunk.js.map
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.54:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_defi-8e4ea1.c6765f15.chunk.js
Source-Map-Adresse: src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_defi-8e4ea1.c6765f15.chunk.js.map

```

**Comment by foxriver76** [comment]
mit 2.9.22 wieder ok?

**Comment by Feuer-sturm** [comment]
Hallo @foxriver76 
mit 2.9.22 und 2.9.23 besteht das Problem weiterhin.

Log Auszug von 2.9.23
```
Layout-Darstellung wurde erzwungen, bevor die Seite vollständig geladen war. Falls Stylesheet noch nicht geladen sind, kann dies zu einem kurzzeitigen Darstellung des Inhalts ohne Formatierung führen. edit.html
iobroker.vis-2@2.9.23 using theme "colored" bootstrap.jsx:16:8

██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
Prompt.js:15:12
Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters Prompt.js:16:12
Help us to create open source project with reactJS! Prompt.js:17:12
See you :) Prompt.js:18:12
[2024-01-24T09:29:47.371Z] Try to connect socket.io.js:66:41
Version vis-google-fonts: 0.0.1 console.ts:40:19
Version vis-history: 1.0.0 console.ts:40:19
Version vis-jqui-mfd: 1.0.12 console.ts:40:19
Version vis-map: 1.0.3 console.ts:40:19
Metro version: "1.2.0" console.ts:40:19
Version justgage: 2.1.0 console.ts:40:19
Version trashschedule: 3.1.3 console.ts:40:19
Version Info-Adapter-Widget: 1.9.26 console.ts:40:19
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools console.ts:40:19
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html console.ts:40:19
Version vis-materialdesign: 0.5.9 console.ts:40:19
common.visWidgets.i18n is deprecated. Use common.visWidgets.scheduler.i18n instead. console.ts:40:19
Uncaught (in promise) TypeError: t.update is not a function
    captureSession baseclient.ts:160
    _sendSessionUpdate hub.ts:661
    endSession hub.ts:598
    startSession hub.ts:630
    init sdk.ts:199
    init sdk.ts:94
    _initializeSentry widgets.min.js:1
    initializeSentry widgets.min.js:1
baseclient.ts:160:14
Translate: Write state console.ts:40:19
Translate: dwd console.ts:40:19
Translate: fancyswitch console.ts:40:19
Translate: history console.ts:40:19
Translate: jqplot console.ts:40:19
Translate: jqui-mfd console.ts:40:19
Translate: justgage console.ts:40:19
Translate: map console.ts:40:19
Translate: materialdesign console.ts:40:19
Translate: metro console.ts:40:19
Translate: spotify-premium console.ts:40:19
Translate: swipe console.ts:40:19
Translate: timeandweather console.ts:40:19
Translate: trashschedule console.ts:40:19
Common user CSS not found: Not exists console.ts:40:19
TypeError: e.visProject[i] is undefined
    u Store.tsx:34
    s Redux
    produce immerClass.ts:92
    Redux 5
    d visUtils.jsx:618
    c visRxWidget.tsx:173
    u src_JaegerDesignCameras_jsx.b89d0855.chunk.js:2
    m src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_defi-8e4ea1.c6765f15.chunk.js:1
    React 8
    V scheduler.production.min.js:13
    T scheduler.production.min.js:14
console.ts:40:19
TypeError: e.visProject[i] is undefined
    u Store.tsx:34
    s Redux
    produce immerClass.ts:92
    Redux 5
    d visUtils.jsx:618
    c visRxWidget.tsx:173
    u src_JaegerDesignCameras_jsx.b89d0855.chunk.js:2
    m src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_defi-8e4ea1.c6765f15.chunk.js:1
    React 8
    V scheduler.production.min.js:13
    T scheduler.production.min.js:14
console.ts:40:19
TypeError: e.visProject[i] is undefined
    u Store.tsx:34
    s Redux
    produce immerClass.ts:92
    Redux 5
    d visUtils.jsx:618
    c visRxWidget.tsx:173
    u src_JaegerDesignCameras_jsx.b89d0855.chunk.js:2
    m src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_defi-8e4ea1.c6765f15.chunk.js:1
    React 8
    V scheduler.production.min.js:13
    T scheduler.production.min.js:14
console.ts:40:19
Uncaught TypeError: e.visProject[i] is undefined
    u Store.tsx:34
    s Redux
    produce immerClass.ts:92
    Redux 5
    d visUtils.jsx:618
    c visRxWidget.tsx:173
    u src_JaegerDesignCameras_jsx.b89d0855.chunk.js:2
    m src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_defi-8e4ea1.c6765f15.chunk.js:1
    React 8
    V scheduler.production.min.js:13
    T scheduler.production.min.js:14
Store.tsx:34:16
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.54:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerDesignCameras_jsx.b89d0855.chunk.js
Source-Map-Adresse: src_JaegerDesignCameras_jsx.b89d0855.chunk.js.map
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.54:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_defi-8e4ea1.c6765f15.chunk.js
Source-Map-Adresse: src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_defi-8e4ea1.c6765f15.chunk.js.map

```

**Comment by foxriver76** [comment]
Hm also habe gerade keine Lizenz aktiv, aber grundsätzlich rendert er die Widgets..

**Comment by foxriver76** [comment]
Kannst du das mit einem Mini Projekt nachstellen und exportieren?

**Comment by Feuer-sturm** [comment]
@obodeldog Wie sieht es bei dir aus. Funktioniert es wieder bei dir mit >= 2.9.22

@foxriver76 Ich konnte das Problem gerade etwas weiter eingrenzen. Ich kann ein neues Projekt anlegen und dort das Jaeger-Design Layout hineinziehen und die Runtime starten.
In meinem Jaeger-Test Projekt macht diese einzelne Seite Probleme, wenn ich diese "aktiviere".
Vor kurzem gab es beim Jaeger-Design ein Adapter update, vielleicht hat es damit etwas zu tun.

Das ist der Seitenexport der Probleme macht
```
{
  "name": "Default",
  "settings": {
    "style": {}
  },
  "widgets": {
    "w000001": {
      "tpl": "tplJaegerDesignLayout",
      "data": {
        "settings": {
          "home": {
            "actions": [
              "80a25c09-f01b-4ac8-bacf-a4053f5358df",
              "5b87fc6a-5b45-4d1d-8891-7d8ce36c4046"
            ],
            "scenes": [
              "c60403d7-6250-417f-9bf7-c2d1dc1abdc1"
            ],
            "showInfo": true,
            "name": "Home"
          },
          "actions": [
            {
              "name": "Licht",
              "subname": "TV",
              "oid": "",
              "id": "80a25c09-f01b-4ac8-bacf-a4053f5358df"
            },
            {
              "name": "Licht",
              "subname": "Haus",
              "oid": "",
              "id": "5b87fc6a-5b45-4d1d-8891-7d8ce36c4046",
              "noActiveState": false
            }
          ],
          "scenes": [
            {
              "name": "Scene",
              "subname": "abc",
              "id": "c60403d7-6250-417f-9bf7-c2d1dc1abdc1",
              "oid": "",
              "saveOrNot": false,
              "noActiveState": false
            }
          ],
          "floors": [
            {
              "name": "EG",
              "buttonName": "EG",
              "icon": "",
              "id": "070381dd-5f57-4474-9d00-f492b8f1c0b9",
              "view": "",
              "showInfo": false,
              "scenes": [
                "c60403d7-6250-417f-9bf7-c2d1dc1abdc1"
              ],
              "actions": [
                "80a25c09-f01b-4ac8-bacf-a4053f5358df",
                "5b87fc6a-5b45-4d1d-8891-7d8ce36c4046"
              ]
            },
            {
              "name": "OG",
              "buttonName": "OG",
              "icon": "",
              "id": "09f9b2e5-2f4f-4762-8273-2d1a805c47a9",
              "view": "",
              "showInfo": false,
              "scenes": [],
              "actions": []
            },
            {
              "name": "Dachboden",
              "buttonName": "Dachboden",
              "icon": "",
              "id": "94851aa3-2d60-44b7-866b-58056976a491",
              "view": "",
              "showInfo": true,
              "scenes": [
                "c60403d7-6250-417f-9bf7-c2d1dc1abdc1"
              ],
              "actions": [
                "80a25c09-f01b-4ac8-bacf-a4053f5358df"
              ]
            }
          ],
          "info": [
            {
              "id": "23a650de-d1b6-488a-9f55-11e29daa3f2f",
              "name": "Lüftung",
              "items": [
                {
                  "name": "Luftfeuchtigkeit",
                  "id": "2a0f4ae9-99cf-4edc-8d12-b464a59019bb",
                  "type": "info",
                  "oid": "hm-rpc.1.INT0000001.1.HUMIDITY",
                  "unit": "%"
                },
                {
                  "name": "Außen Temp",
                  "id": "5f312b28-3248-4b10-8838-8bd17f77d927",
                  "type": "info",
                  "true": {},
                  "false": {},
                  "oid": "valloxmv.0.A_CYC_TEMP_OUTDOOR_AIR",
                  "unit": "°C"
                }
              ]
            },
            {
              "id": "83cb65b5-e442-4a13-b656-28a4459189ab",
              "name": "Urlaub",
              "items": [
                {
                  "name": "Urlaub",
                  "id": "4a8c920c-6ac5-4e53-95d0-f45a3ad4c7e4",
                  "true": {
                    "text": "Urlaubmodus an"
                  },
                  "false": {
                    "text": "Urlaubsmodus Aus"
                  },
                  "type": "text",
                  "oid": "0_userdata.0.temp2.Vacation"
                }
              ]
            }
          ],
          "menu": [
            {
              "name": "Home",
              "icon": "",
              "iconSize": "Home",
              "position": "top",
              "type": "home",
              "filter": "",
              "showInfo": "inherit",
              "id": "a1d585be-c0d1-4c47-a289-abe42a81947a"
            },
            {
              "name": "Etagen",
              "icon": "",
              "iconSize": "",
              "position": "top",
              "type": "page",
              "filter": "",
              "showInfo": "inherit",
              "id": "64454f26-ff77-4b58-9256-ecb4ac3855a4"
            },
            {
              "name": "Testseite",
              "icon": "",
              "iconSize": "",
              "position": "top",
              "type": "simplepage",
              "filter": "",
              "showInfo": false,
              "id": "b4834a20-d242-4309-b511-b7819027b198",
              "view": "Neue Seite"
            }
          ],
          "settings": {
            "theme": "green-dark",
            "iconRatio": 46.7,
            "mainBackground": "#ffffff",
            "textColor": "#232A38",
            "blockBackground": "#F2F2F2",
            "textColorGray": "#C1CBD8",
            "alarmColor": "#F0134D",
            "okColor": "#08aa11",
            "menuBackground": "#232A38",
            "menuTextColor": "#ffffff",
            "sceneSaveBackground": "#C1CBD8",
            "iconInactiveColor": "#707070",
            "iconActiveColor": "#ffffff",
            "iconInactiveBack": "#ffffff",
            "mainColor": "#46C34D",
            "hideTime": false,
            "floorName": ""
          }
        },
        "g_common": true,
        "bindings": []
      },
      "style": {
        "left": 1,
        "top": 5,
        "width": "100%",
        "height": "100%",
        "bindings": []
      },
      "widgetSet": "vis-2-widgets-jaeger-design"
    }
  },
  "activeWidgets": {}
}
```

**Comment by Feuer-sturm** [comment]
@foxriver76 Hab gerade mal ein paar Downgrades auf Jaeger-Design 1.1.0 und 1.1.5 gemacht. Aber auch mit den Versionen bekomme ich meine Fehlermeldungen.

**Comment by foxriver76** [comment]
Wenn du ne neue Seite in deinem Projekt Jäger Test Projekt machst, gehen sie da?

Ich kann es demnächst mal ausprobieren mit deinem Export.

**Comment by Feuer-sturm** [comment]
@foxriver76 Ja ich kann neue Seiten im Jaeger Projekt hinzufügen und dort auch Elemente hinzufügen. Es muss irgendein widget sein das Probleme macht welches auf der Seite liegt, welche ich exportiert habe.

**Comment by foxriver76** [comment]
So wie ich die Fehlermeldung deute könnte es auch der view selbst sein. Aber kann die Tage checken

**Comment by obodeldog** [comment]
Leider geht es auch mit der neusten Version nicht:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/35403739/59c8bdf4-4242-4e97-9541-3d42c257a1a7)
