### ISSUE TITLE
[bug]: can't render tplMetroTileNav

### ISSUE THREAD

**Issue by BassT23** [ioBroker/ioBroker.vis-2#483]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Hi @ll,

seit dem letzten update von vis-2 (v2.9.64)

habe ich haufenweise fehlermeldungen:

(siehe log file)

Metro Tile Nav buttens werden nicht mehr angezeigt, ...
reinstall von metro widget (v1.2.0) hilft nicht :(

### To Reproduce

metro widget in vis-2 einfügen/benutzen

### Expected behavior

metro widgets sollten wieder funktionieren ;)

### Screenshots & Logfiles

```
web.1 | 2024-10-24 19:23:32.381 | error | 10 - at Function.renderTo (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1449:63)
web.1 | 2024-10-24 19:23:32.376 | error | 9 - at r (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1370:22)
web.1 | 2024-10-24 19:23:32.376 | error | 8 - at Function.frag (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1405:22)
web.1 | 2024-10-24 19:23:32.375 | error | 7 - at Function.hookup (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1418:19)
web.1 | 2024-10-24 19:23:32.375 | error | 6 - at a.each (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:343:211)
web.1 | 2024-10-24 19:23:32.375 | error | 5 - at HTMLDivElement.<anonymous> (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1419:98)
web.1 | 2024-10-24 19:23:32.375 | error | 4 - at http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1727:17
web.1 | 2024-10-24 19:23:32.372 | error | 3 - at a.each (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:343:211)
web.1 | 2024-10-24 19:23:32.372 | error | 2 - at Function.<anonymous> (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1728:17)
web.1 | 2024-10-24 19:23:32.372 | error | 1 - at Object.eval (tplMetroTileNav.js:21:77)
web.1 | 2024-10-24 19:23:32.370 | error | 0 - TypeError: vis.binds.basic.navigation is not a functionTypeError: vis.binds.basic.navigation is not a function
web.1 | 2024-10-24 19:23:32.368 | error | can't render tplMetroTileNav w000032 on "101_Navi":
```

### Adapter version

v2.9.64

### js-controller version

6.0.11

### Node version

9.6.7

### Operating system

ubuntu server

**Comment by BassT23** [comment]
Nach update von node auf v20 besteht das problem weiterhin :(

**Comment by Sputnik24** [comment]
Ich habe das Problem ebenfalls und es müllt das ganze Log zu.

**Comment by allewelt** [comment]
Gleiches Problem, Metro-Widges lassen sich nicht anzeigen, leere Felder, seitenweise Abbruch-Log-Sätze. Sowohl bei stable-Version aller Instanzen, als auch bei den  beta-Versionen.

**Comment by mcm1957** [comment]
An sich erfordern Widgets potenziell eine Anpassung für vis-2. Da die letzte Bearbeiten des Adapters vis-metro 2022 erfolgt ist ist fraglich ob diese Widgets jemals an vis-2 angepasst wurden.

In jedem Fall dürfte das eher ein Problem sein, dass in ioBroker.vis-metro zu fixen ist und auch dort ein Issue wert wäre. (Dagegen spricht dass es mit früheren vis-2 Versionen anscheinend ging).

**Comment by allewelt** [comment]
Lief  bei mir bis vor ein paar Tagen einwandfrei mit vis-2. Hatte dann irgendwas upgedated  (kann leider nicht den Auslöser sagen) - danach dann ging es nicht mehr. Komischerweise werden im EDIT-Mode die Kacheln angezeigt und funktionieren beim "Direktstart" aus dem Edit auch.

**Comment by dodi666** [comment]
Hi, hat jemand eine Idee, ob das Problem gefixed werden kann? Ich habe nämlich aktuell keine Idee wie ich nach vis2.0 migrieren soll, wenn die Metro Widgets nicht mehr funktionieren...
Danke und Grüße

**Comment by typhosj** [comment]
Das ist derselbe Fehler wie in #395 (gleiches Widget `tplMetroTileNav`) und #549 (VIS-Metro allgemein seit ~2.9.30/2.9.39).

Es wäre übersichtlicher, die drei Meldungen in einem Issue zu führen. Wie mcm1957 hier und in #549 schon geschrieben hat, liegt das Problem im Adapter `ioBroker.vis-metro`, der nie an vis-2 angepasst wurde.
