### ISSUE TITLE
[bug]: Runtime öffnen - URL der page unvollständig/abgeschnitten

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.vis-2#502]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Mit V2.11.1 lassen sich bei mir die Seiten nicht mehr aus dem Editor heraus über den Button "Runtime in neuem Fenster öffnen" anzeigen.

Die URL wird in der Adresszeile vom neuen Browserfenster nach dem Projektnamen direkt nach dem # Zeichen abgeschnitten, somit erfolgt auch kein Seitenaufruf

Beispiel vollständiger Pfad in der Adresszeile müsste sein:
`http://192.168.178.33:8082/vis-2/?TestProject#TestPage`

Beim Drücken des Buttons erscheint aber nur folgender Pfad:
`http://192.168.178.33:8082/vis-2/?TestProject# `

Gibt man die URL in der Browser Adresszeile bei der VIS Runtime als vollständigen Pfad ein, läuft die Runtime auch korrekt.

Bei einem neu angelegten Projekt wird dagegen beim Runtime Button immer nur die standardmäßig vorhandene Seite "default" aufgerufen statt der im Editor geöffneten Seite.

### To Reproduce

 Siehe Bug Beschreibung.

### Expected behavior

Button "Runtime in neuem Fenster öffnen" sollte die URL korrekt in die Adresszeile des Browserfensters übergeben.

### Screenshots & Logfiles

**Button "Runtime in neuem Fenster öffnen"**

![Screenshot 2024-12-05 185308](https://github.com/user-attachments/assets/4c4d6dc9-fed1-4a32-8341-19e140ba96c3)

Version 2.11.1 wird übrigens im Editor auch noch nicht korrekt angezeigt,

**Browserkonsole beim (fehlerhaften) Aufruf der Seite / Adresszeile**
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at Editor.tsx:621:63
    at Array.forEach (<anonymous>)
    at U.findViewWithNearestResolution (Editor.tsx:614:38)
    at U.loadProject (Editor.tsx:708:40)
    at async U.onConnectionReady (Editor.tsx:918:44)
```

### Adapter version

2.11.1

### js-controller version

7.0.4

### Node version

20.18.1

### Operating system

Debian 12

### Additional context

Darüber hinaus kann bei allen VIS Versionen nach der V2.9.64 auch kein Android shortcut auf dem Homescreen mehr erzeugt werden (add to homescreen), egal mit welchem Browser auf dem Handy. 

Hier ist die für den shortcut erzeugte URL immer direkt nach …/vis-2/ abgeschnitten. Somit wird auch keine Seite geladen, es erscheint nur das drehende iobroker Logo.

Dieser Fehler wurde auch schon in issue 102 in ähnlicher Weise beschrieben und von mir am 24.11.2024 bezüglich der Versionen nach V2.9.64 noch etwas ergänzt. https://github.com/ioBroker/ioBroker.vis-2/issues/102

**Comment by Bernd9000** [comment]
Dito, das mit der Runtime habe ich auch.
Bei mir erscheint folgender Fehler in Firefox:

```
Uncaught (in promise) TypeError: e[s].settings.sizey is undefined
findViewWithNearestResolution Editor.tsx:621
findViewWithNearestResolution Editor.tsx:614
loadProject Editor.tsx:708
Editor.tsx:621:33
```


Adapter version
2.11.1

js-controller version
7.0.4

Node version
20.18.1

Operating system
Windows 11

**Comment by Bernd9000** [comment]
@MK-66 
Ich glaube ein Fehler habe ich gefunden.
Ist bei Dir im Projekt eine Navigationsleiste aktiv ?

**Comment by Bernd9000** [comment]
Zumindest ein Fehler hab ich gefunden wo die web Adresse nach `#` abgeschnitten ist beim drücken auf Runtime.
Es betrifft Seiten bei denen man in den Attributen unter Optionen "Standart" angehackt hat.

![Image](https://github.com/user-attachments/assets/aa8f23c3-b508-4fbc-b81b-9d3b22666967)


Teilausschnitt einer Seite in der "vis-views.json" wie es dann sein sollte:

```
 "Aussen 1": {
    "name": "",
    "settings": {
      
      "useAsDefault": true,
      "sizex": 1281,
      "sizey": "720",
```

Es gibt allerdings Seiten in denen hier bei mir sizex und sizey fehlen.
Da kommt es dann  in der "Editor.tsx" zum Problem an dieser Stelle (ab Zeile 614):

Teilausschnitt:
```
Object.keys(project).forEach(view => {
              
                    if (
                        project[view].settings?.useAsDefault &&
                        // If difference less than 20%
                        parseInt(project[view].settings.sizey.toString(), 10) &&
                        Math.abs(
                            ratio -
                                parseInt(project[view].settings.sizex.toString(), 10) /
                                    parseInt(project[view].settings.sizey.toString(), 10),
                        ) < difference
```
Hier hat "sizey" und "sizex" den Wert `undefined` und das löst den Fehler aus.
Das selbe nochmal bei Zeile 621


Die Lösung wäre also erstmal zu schauen bei welchen Seiten man die Option "Standart" gesetzt hat.
Und im Code sollte vorher überprüft werden ob einer der Werte `undefined` ist.
