### ISSUE TITLE
Trashschedule Widget (vis-2-beta.0: v2.0.23)

### ISSUE THREAD

**Issue by DaisyMaus** [ioBroker/ioBroker.vis-2#58]
Hallo

Das Trashschedule Widget wird in der Vis2 Bearbeitenoberfäche angezeigt aber oft erst nach mehrmaligen aktualisieren in der Anzeigeoberfläche

Adapter version: trashschedule.0 v2.2.0
JS-Controller version : 4.0.24
Node version : v18.15.0
NPM : 9.5.0
vis-2-beta.0 : v2.0.23

Gruss Sandy

﻿bootstrap.jsx:20 iobroker.vis-2-beta@2.0.24 using theme "dark"
main.9e02fddc.js:658 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

main.9e02fddc.js:658 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
main.9e02fddc.js:658 Help us to create open source project with reactJS!
main.9e02fddc.js:658 See you :)
VM55:140 Version vis-canvas-gauges: 0.1.5
VM56:78 Version vis-colorpicker: 2.0.3
VM60:110 Version vis-jqui-mfd: 1.0.12
VM62:45 Version vis-map: 1.0.3
VM63:645 Metro version: "1.2.0"
VM64:97 Version vis-plumb: 1.0.0
VM67:1269 Version vis-weather: 2.5.6
trashschedule.js:163 Version trashschedule: 2.2.0
material.js:31 Version material: 0.1.5
justgage.js:115 Version justgage: 1.0.2
info.js:29 Version Info-Adapter-Widget: 0.0.9
lib.min.js:44 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
lib.min.js:44 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
materialdesign.js:33 Version vis-materialdesign: 0.5.76
widgets.min.js:1 vis-materialdesign: vibration supported by device: 'true'
widgets.min.js:1 vis-materialdesign: sentry datapoint 'vis-materialdesign.0.sentry' not exist! Go to the adapter settings to activate it.
initializeSentry @ widgets.min.js:1
widgets.min.js:1 vis-materialdesign: click audio file '/vis.0/materialdesign-widgets-click-sound.mp3' not exists!
(anonymous) @ widgets.min.js:1
visEngine.jsx:1720 Common user CSS not found: Not exists
(anonymous) @ visEngine.jsx:1720
visEngine.jsx:1594 [2023-04-11T20:19:09.257Z] +SUBSCRIBE: tr-064.0.devices.Nico-Galaxy-S22.active
visEngine.jsx:1594 [2023-04-11T20:19:09.264Z] +SUBSCRIBE: hm-rega.0.22483
visEngine.jsx:1594 [2023-04-11T20:19:09.270Z] +SUBSCRIBE: ems-esp.0.heatingCircuits.hc1.roomtemperature
visEngine.jsx:1594 [2023-04-11T20:19:09.272Z] +SUBSCRIBE: hm-rpc.0.OEQ0662018.4.ACTUAL_TEMPERATURE
visEngine.jsx:1594 [2023-04-11T20:19:09.273Z] +SUBSCRIBE: hm-rpc.0.OEQ0662021.4.ACTUAL_TEMPERATURE
visEngine.jsx:1594 [2023-04-11T20:19:09.274Z] +SUBSCRIBE: hm-rpc.0.OEQ1251536.4.ACTUAL_TEMPERATURE
visEngine.jsx:1594 [2023-04-11T20:19:09.275Z] +SUBSCRIBE: hm-rpc.0.OEQ1251558.4.ACTUAL_TEMPERATURE
visEngine.jsx:1594 [2023-04-11T20:19:09.276Z] +SUBSCRIBE: ems-esp.0.system.sensors.temperatures.outdoor_t1
visEngine.jsx:1594 [2023-04-11T20:19:09.277Z] +SUBSCRIBE: midea.0.20890720963876.status.outdoorTemperature
visEngine.jsx:1594 [2023-04-11T20:19:09.277Z] +SUBSCRIBE: scene.0.Alarm.Einbrecher_Scheinwerfer
visEngine.jsx:1594 [2023-04-11T20:19:09.278Z] +SUBSCRIBE: hm-rpc.0.BidCoS-RF.8.PRESS_SHORT
visEngine.jsx:1594 [2023-04-11T20:19:09.294Z] +SUBSCRIBE: hm-rpc.0.OEQ2138145.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.294Z] +SUBSCRIBE: hm-rpc.0.OEQ2138145.1.LOWBAT
hqwidgets.js:909 Version vis-hqwidgets: 1.2.0
visEngine.jsx:1594 [2023-04-11T20:19:09.295Z] +SUBSCRIBE: hm-rpc.0.OEQ1980740.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.299Z] +SUBSCRIBE: hm-rpc.0.OEQ0924753.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.300Z] +SUBSCRIBE: hm-rpc.0.OEQ0923521.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.301Z] +SUBSCRIBE: hm-rpc.0.OEQ0923598.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.302Z] +SUBSCRIBE: hm-rpc.0.OEQ0923572.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.302Z] +SUBSCRIBE: hm-rpc.0.NEQ1158750.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.303Z] +SUBSCRIBE: hm-rpc.0.NEQ1158750.1.LOWBAT
visEngine.jsx:1594 [2023-04-11T20:19:09.303Z] +SUBSCRIBE: hm-rpc.0.OEQ0923620.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.304Z] +SUBSCRIBE: hm-rpc.0.OEQ0923542.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.305Z] +SUBSCRIBE: hm-rpc.0.OEQ0924873.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.306Z] +SUBSCRIBE: hm-rpc.0.OEQ0923538.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.307Z] +SUBSCRIBE: hm-rpc.0.OEQ1949386.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.314Z] +SUBSCRIBE: hm-rpc.0.OEQ0589916.2.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.318Z] +SUBSCRIBE: hm-rpc.0.OEQ1150596.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.322Z] +SUBSCRIBE: hm-rpc.0.OEQ0589916.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.326Z] +SUBSCRIBE: sonoff.0.Gosund_Heizung_Flur.POWER
visEngine.jsx:1594 [2023-04-11T20:19:09.329Z] +SUBSCRIBE: sonoff.0.Gosund_Heizung_Esszimmer.POWER
visEngine.jsx:1594 [2023-04-11T20:19:09.331Z] +SUBSCRIBE: hm-rpc.0.NEQ1550558.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.338Z] +SUBSCRIBE: hm-rpc.0.REQ1016998.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.339Z] +SUBSCRIBE: hm-rpc.0.OEQ0591283.2.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.341Z] +SUBSCRIBE: hm-rpc.0.OEQ1149005.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.343Z] +SUBSCRIBE: hm-rpc.0.OEQ0624137.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.346Z] +SUBSCRIBE: hm-rpc.0.OEQ0591283.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.351Z] +SUBSCRIBE: hm-rpc.0.OEQ0624129.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.356Z] +SUBSCRIBE: hm-rpc.0.OEQ1151791.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.357Z] +SUBSCRIBE: hm-rpc.0.NEQ1550561.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.358Z] +SUBSCRIBE: hm-rpc.0.REQ1015789.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.363Z] +SUBSCRIBE: ical.0.data.html
visEngine.jsx:1594 [2023-04-11T20:19:09.384Z] +SUBSCRIBE: hm-rpc.0.OEQ1949335.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.386Z] +SUBSCRIBE: daswetter.0.Wetter_1
visEngine.jsx:1594 [2023-04-11T20:19:09.537Z] +SUBSCRIBE: hm-rpc.0.OEQ2235719.1.STATE
VM66:127 Version vis-timeandweather: 1.2.1
visEngine.jsx:1594 [2023-04-11T20:19:09.632Z] +SUBSCRIBE: daswetter.0.Wetter_2
visEngine.jsx:1594 [2023-04-11T20:19:09.634Z] +SUBSCRIBE: hm-rpc.0.REQ0190994.1.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.638Z] +SUBSCRIBE: hm-rpc.0.REQ0190994.2.STATE
visEngine.jsx:1594 [2023-04-11T20:19:09.644Z] +SUBSCRIBE: hm-rpc.0.NEQ1277173.1.STATE
leer.jpg:1     Failed to load resource: the server responded with a status of 404 (Not Found)
query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(%27664942%27)%20and%20u%3D%27c%27&rnd=20233222&format=json&callback=jQuery111205322768206794195_1681244346212&_=1681244346213:1     Failed to load resource: net::ERR_NAME_NOT_RESOLVED
adview:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
widgets.min.js:1 [waitForWidgets] stop waiting for vis widgets after 500 retries
waitForWidgets @ widgets.min.js:1
visEngine.jsx:1594 [2023-04-11T20:19:15.309Z] +SUBSCRIBE: hm-rpc.0.REQ1015789.2.STATE
visEngine.jsx:1594 [2023-04-11T20:19:15.329Z] +SUBSCRIBE: trashschedule.0.type.json
jquery-1.11.2.min.js:2 Uncaught TypeError: Cannot read properties of null (reading 'length')
    at Function.each (jquery-1.11.2.min.js:2:2821)
    at Object.redraw (trashschedule.js:354:15)
    at Object.createWidget (trashschedule.js:192:36)
    at trashschedule.js:172:44
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/static/js/main.9e02fddc.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_i18n_de_json-src_i18n_en_json-src_i18n_es_json-src_i18n_fr_json-src_i18n_it_json-src_i18n-67bb96.1677e5d1.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Thermostat_jsx.00661837.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Static_jsx.de18c1d2.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Actual_jsx.29743391.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Switches_jsx.9f8f5c4d.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Clock_jsx.93e562af.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Blinds_jsx.66f75413.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_ViewInWidget_jsx.ed9f4f18.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_SimpleState_jsx.034a9b74.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Camera_jsx.9abd0ce3.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_translations_js.4825f038.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Security_jsx.8203d3a4.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Generic_jsx-src_ObjectChart_jsx.bdb36970.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Player_jsx.53f18e7b.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Html_jsx.151c713c.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/fullcalendar/static/js/src_translations_js.6c21cc8a.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/fullcalendar/static/js/src_i18n_de_json-src_i18n_en_json-src_i18n_es_json-src_i18n_fr_json-src_i18n_it_json-src_i18n-67bb96.54ee2f4a.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/fullcalendar/static/js/src_FullCalendar_jsx-node_modules_mui_utils_useControlled_js-node_modules_mui_utils_useEventC-5a34fa.267d82f6.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/fullcalendar/static/js/src_Component_Calendar_js-webpack_sharing_consume_default_iobroker_vis-2-widgets-react-dev_io-4dd1d1.5f830bb3.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_i18n_de_json-src_i18n_en_json-src_i18n_es_json-src_i18n_fr_json-src_i18n_it_json-src_i18n-67bb96.0e530749.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_translations_js.dab10b42.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_ConsumptionComparison_jsx.0f071e3f.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_IntervalSelector_jsx.4e7481ae.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_Consumption_jsx.79ef8c21.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_translations_js.9bdd0318.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_Distribution_jsx.6b5ce11d.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_i18n_de_json-src_i18n_en_json-src_i18n_es_json-src_i18n_fr_json-src_i18n_it_json-src_i18n-67bb96.d19fe4f4.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_ColorGauge_jsx.63c3ad5c.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_WaterGauge_jsx.6107aae7.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_BatteryGauge_jsx.cf07ea6e.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.43:8082/vis-2-beta/widgets/vis-2-widgets-material/static/css/src_Map_jsx-node_modules_leaflet_dist_leaflet_css.11ebe247.chunk.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by klein0r** [comment]
FYI: Ich plane eh das Widget für VIS2 komplett neu zu entwickeln

**Comment by TjadenVdF** [comment]
Ich habe das gleiche Problem im Dezember 2024. Da ich gerade auf VIS-2 umsteige fiel mir der Fehler erst jetzt auf. 

Das Widget habe ich auf der Startseite liegen. Es wird aber erst gerendert, wenn ich einmal auf eine andere Seite navigiere und dann wieder zurückkehre. Das ist unschön. Ich werde mir dann wohl leider etwas anderes ausdenken müssen.

**Comment by Cisalpinos** [comment]
Gleiche Verhalten hier, war mir auch so. Nach dem Einspielen der aktuellen Entwicklerversion (2.11.2) funktioniert das bei mir problemlos. 
(Ob man sich dafür andere Probleme einfängt, da es eine Entwicklerversion ist, kann ich nicht sagen. Bei mir sind jedenfalls keine zusätzlichen Fehler aufgetreten)
VG

**Comment by augenwursthans-ai** [comment]
> Ich habe das gleiche Problem im Dezember 2024. Da ich gerade auf VIS-2 umsteige fiel mir der Fehler erst jetzt auf.
> 
> Das Widget habe ich auf der Startseite liegen. Es wird aber erst gerendert, wenn ich einmal auf eine andere Seite navigiere und dann wieder zurückkehre. Das ist unschön. Ich werde mir dann wohl leider etwas anderes ausdenken müssen.

Bei mir verhält es sich auch so. Adapter in der aktuellen Version 3.3.0. 
Gab es eine Lösung?

**Comment by typhosj** [comment]
Hallo, ich habe den Adapter (mit Widget) unter https://github.com/typhosj/ioBroker.trashschedule geforkt und Änderungen vorgenommen, sodass das Widget bei mir unter Vis2 direkt beim ersten Laden der Seite problemlos funktioniert. Ein PR zu klein0rs Repository ist gestellt, aber noch nicht angenommen worden. Vielleicht hilft es euch ja, das Widget von der genannten URL zu installieren und die Änderungen auszuprobieren.

VG
