### ISSUE TITLE
VIS 2: Log-Fehler für vermutlich ein "Gauge"? In VIS 1 läuft das fehlerfrei.

### ISSUE THREAD

**Issue by MichaelSchaaf999** [ioBroker/ioBroker.vis-2#63]
**Describe the bug**  
web.0
2023-07-06 08:02:14.902 error Error: can't update states object for zoe2.0.VF1AG000X65218215.charge_level(TypeError: RGraph.Effects.Gauge is undefined😞 "tplRGgauge/elem.rgraphValueChange@http://192.168.178.201:8082/vis-2-beta/edit.html?ALF1#ALF1_Solaranzeige_4 line 1 > injectedScript:973:21\nonchange@http://192.168.178.201:8082/vis-2-beta/edit.html?ALF1#ALF1_Solaranzeige_4 line 1 > injectedScript:138:30\n36167/i/n.onStateChange/<@[http://192.168.178.201:8082/vis-2-beta/static/js/167.5a545327.chunk.js:1:348602\n36167/i/n.onStateChange@http://192.168.178.201:8082/vis-2-beta/static/js/167.5a545327.chunk.js:1:348575\n83251/value/](http://192.168.178.201:8082/vis-2-beta/static/js/167.5a545327.chunk.js:1:348602%5Cn36167/i/n.onStateChange@http://192.168.178.201:8082/vis-2-beta/static/js/167.5a545327.chunk.js:1:348575%5Cn83251/value/)<@[http://192.168.178.201:8082/vis-2-beta/static/js/main.98b40ce7.js:2:721569\nvalue@http://192.168.178.201:8082/vis-2-beta/static/js/main.98b40ce7.js:2:721543\n83251/value/](http://192.168.178.201:8082/vis-2-beta/static/js/main.98b40ce7.js:2:721569%5Cnvalue@http://192.168.178.201:8082/vis-2-beta/static/js/main.98b40ce7.js:2:721543%5Cn83251/value/)</<@[http://192.168.178.201:8082/vis-2-beta/static/js/main.98b40ce7.js:2:713606\ni@http://192.168.178.201:8082/vis-2-beta/static/js/618.b9cdaf52.chunk.js:2:90250\n](http://192.168.178.201:8082/vis-2-beta/static/js/main.98b40ce7.js:2:713606%5Cni@http://192.168.178.201:8082/vis-2-beta/static/js/618.b9cdaf52.chunk.js:2:90250%5Cn)"
web.0
2023-07-06 08:00:08.960 error Error: can't update states object for zoe2.0.VF1AG000X65218215.charge_level(TypeError: Cannot read properties of undefined (reading 'Grow')): "TypeError: Cannot read properties of undefined (reading 'Grow')\n at elem.rgraphValueChange (<anonymous>:973:42)\n at Object.onchange [as callback] (<anonymous>:138:30)\n at [http://192.168.178.201:8082/vis-2-beta/static/js/167.5a545327.chunk.js:1:348602\n](http://192.168.178.201:8082/vis-2-beta/static/js/167.5a545327.chunk.js:1:348602%5Cn) at Array.forEach (<anonymous>)\n at n.onStateChange (http://192.168.178.201:8082/vis-2-beta/static/js/167.5a545327.chunk.js:1:348575)\n at [http://192.168.178.201:8082/vis-2-beta/static/js/main.98b40ce7.js:2:721568\n](http://192.168.178.201:8082/vis-2-beta/static/js/main.98b40ce7.js:2:721568%5Cn) at Array.forEach (<anonymous>)\n at t.value (http://192.168.178.201:8082/vis-2-beta/static/js/main.98b40ce7.js:2:721543)\n at [http://192.168.178.201:8082/vis-2-beta/static/js/main.98b40ce7.js:2:713606\n](http://192.168.178.201:8082/vis-2-beta/static/js/main.98b40ce7.js:2:713606%5Cn) at i (http://192.168.178.201:8082/vis-2-beta/static/js/618.b9cdaf52.chunk.js:2:90250)"

**To Reproduce**  
View(s) von VIS 1 in VIS 2: Wirft Fehler.

**Expected behavior**  
-

**Screenshots & Logfiles**  
-

**Versions:**  
 - Adapter version: vis-2-beta <v2.1.2>
...

**Additional context**  
-

**Comment by Feuer-sturm** [comment]
@MichaelSchaaf999 please check with vis-2 adapter version 2.2.2 if this issue is still there.
If yes, we can reopen the issue.

**Comment by MichaelSchaaf999** [comment]
@Feuer-sturm: I still see this...
<html><head></head><body>

  | Zeit |  
-- | -- | --


</body></html>
<html><head></head><body>

web.0 | 2023-08-20 18:22:38.737 | error | Error:  can't update states object for  mercedesme.0.W1N2477861J177165.state.soc.displayValue(TypeError:  RGraph.Effects.Gauge is undefined):  "tplRGgauge/elem.rgraphValueChange@http://192.168.178.201:8082/vis-2/index.html#ALF1_Beleuchtung  line 1 >  injectedScript:973:21\nonchange@http://192.168.178.201:8082/vis-2/index.html#ALF1_Beleuchtung  line 1 >  injectedScript:138:30\n6664/i/n.onStateChange/<@http://192.168.178.201:8082/vis-2/static/js/664.6b25b46d.chunk.js:1:160851\n6664/i/n.onStateChange@http://192.168.178.201:8082/vis-2/static/js/664.6b25b46d.chunk.js:1:160824\n83251/value/<@http://192.168.178.201:8082/vis-2/static/js/main.f9499e59.js:2:749815\nvalue@http://192.168.178.201:8082/vis-2/static/js/main.f9499e59.js:2:749789\n83251/value/</<@http://192.168.178.201:8082/vis-2/static/js/main.f9499e59.js:2:740314\na@http://192.168.178.201:8082/vis-2/static/js/563.908bf4f9.chunk.js:2:77578\n"
-- | -- | -- | --
web.0 | 2023-08-20 18:21:35.669 | error | Error:  can't update states object for  mercedesme.0.W1N2477861J177165.state.soc.displayValue(TypeError:  RGraph.Effects.Gauge is undefined):  "tplRGgauge/elem.rgraphValueChange@http://192.168.178.201:8082/vis-2/edit.html#ALF1_Beleuchtung_WoZi  line 1 >  injectedScript:973:21\nonchange@http://192.168.178.201:8082/vis-2/edit.html#ALF1_Beleuchtung_WoZi  line 1 >  injectedScript:138:30\n66415/i/n.onStateChange/<@http://192.168.178.201:8082/vis-2/static/js/415.b97e7b6e.chunk.js:1:327714\n66415/i/n.onStateChange@http://192.168.178.201:8082/vis-2/static/js/415.b97e7b6e.chunk.js:1:327687\n83251/value/<@http://192.168.178.201:8082/vis-2/static/js/main.3dde8f41.js:2:749815\nvalue@http://192.168.178.201:8082/vis-2/static/js/main.3dde8f41.js:2:749789\n83251/value/</<@http://192.168.178.201:8082/vis-2/static/js/main.3dde8f41.js:2:740314\ni@http://192.168.178.201:8082/vis-2/static/js/168.f0747832.chunk.js:2:95252\n"
web.0 | 2023-08-20 18:21:22.368 | error | Error:  can't update states object for  mercedesme.0.W1N2477861J177165.state.soc.displayValue(TypeError: Cannot  read properties of undefined (reading 'Grow')): "TypeError: Cannot read  properties of undefined (reading 'Grow')\n    at elem.rgraphValueChange  (<anonymous>:973:42)\n    at Object.onchange [as callback]  (<anonymous>:138:30)\n    at  http://192.168.178.201:8082/vis-2/static/js/664.6b25b46d.chunk.js:1:160851\n     at Array.forEach (<anonymous>)\n    at n.onStateChange  (http://192.168.178.201:8082/vis-2/static/js/664.6b25b46d.chunk.js:1:160824)\n     at  http://192.168.178.201:8082/vis-2/static/js/main.f9499e59.js:2:749814\n     at Array.forEach (<anonymous>)\n    at t.value  (http://192.168.178.201:8082/vis-2/static/js/main.f9499e59.js:2:749789)\n     at  http://192.168.178.201:8082/vis-2/static/js/main.f9499e59.js:2:740314\n     at a  (http://192.168.178.201:8082/vis-2/static/js/563.908bf4f9.chunk.js:2:77578)"

</body></html>

**Comment by MichaelSchaaf999** [comment]
I don't refer to "mercedesme"-adapter/datapoint in this view "Beleuchtung_WoZi" and I cannot find any text like this  in the code...
What else can I do?

<html><head></head><body>

web.0 | 2023-08-21 10:37:18.260 | error | Error:  can't update states object for  mercedesme.0.W1N2477861J177165.state.soc.displayValue(TypeError:  RGraph.Effects.Gauge is undefined):  "tplRGgauge/elem.rgraphValueChange@http://192.168.178.201:8082/vis-2/edit.html#ALF1_Beleuchtung_WoZi  line 1 >  injectedScript:973:21\nonchange@http://192.168.178.201:8082/vis-2/edit.html#ALF1_Beleuchtung_WoZi  line 1 >  injectedScript:138:30\n66415/i/n.onStateChange/<@http://192.168.178.201:8082/vis-2/static/js/415.b97e7b6e.chunk.js:1:327714\n66415/i/n.onStateChange@http://192.168.178.201:8082/vis-2/static/js/415.b97e7b6e.chunk.js:1:327687\n83251/value/<@http://192.168.178.201:8082/vis-2/static/js/main.3dde8f41.js:2:749815\nvalue@http://192.168.178.201:8082/vis-2/static/js/main.3dde8f41.js:2:749789\n83251/value/</<@http://192.168.178.201:8082/vis-2/static/js/main.3dde8f41.js:2:740314\ni@http://192.168.178.201:8082/vis-2/static/js/168.f0747832.chunk.js:2:95252\n"
-- | -- | -- | --
web.0 | 2023-08-21 10:34:05.517 | error | Error:  can't update states object for  mercedesme.0.W1N2477861J177165.state.soc.displayValue(TypeError:  RGraph.Effects.Gauge is undefined):  "tplRGgauge/elem.rgraphValueChange@http://192.168.178.201:8082/vis-2/edit.html#ALF1_Beleuchtung_WoZi  line 1 >  injectedScript:973:21\nonchange@http://192.168.178.201:8082/vis-2/edit.html#ALF1_Beleuchtung_WoZi  line 1 >  injectedScript:138:30\n66415/i/n.onStateChange/<@http://192.168.178.201:8082/vis-2/static/js/415.b97e7b6e.chunk.js:1:327714\n66415/i/n.onStateChange@http://192.168.178.201:8082/vis-2/static/js/415.b97e7b6e.chunk.js:1:327687\n83251/value/<@http://192.168.178.201:8082/vis-2/static/js/main.3dde8f41.js:2:749815\nvalue@http://192.168.178.201:8082/vis-2/static/js/main.3dde8f41.js:2:749789\n83251/value/</<@http://192.168.178.201:8082/vis-2/static/js/main.3dde8f41.js:2:740314\ni@http://192.168.178.201:8082/vis-2/static/js/168.f0747832.chunk.js:2:95252\n"

</body></html>
