### ISSUE TITLE
Import von Widgets nicht möglich

### ISSUE THREAD

**Issue by PiemurIsBack** [ioBroker/ioBroker.vis-2#88]
**Describe the bug**  
Ich versuche ein Widget zu importieren und bekomme direkt nach dem anklicken "Widget import" eine Fehlermeldung (F12).
lib/js/ace/worker-json.js' failed to load.
Das Importieren funktioniert nicht.

**To Reproduce**  
1. Widget import
2. Click on F12
3. Insert Widget-Code
4. Scroll down 
5. See error

**Expected behavior**  

**Screenshots & Logfiles**  

````
iobroker.vis-2@2.2.7 using theme "colored"
Prompt.js:14 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:15 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:16 Help us to create open source project with reactJS!
Prompt.js:17 See you :)
socket.io.js:66 [2023-09-23T08:17:36.949Z] Try to connect
instrument.ts:144 Version vis-colorpicker: 2.0.3
instrument.ts:144 Metro version: "1.2.0"
instrument.ts:144 Version trashschedule: 2.2.0
instrument.ts:144 Version Info-Adapter-Widget: 0.0.9
instrument.ts:144 Version vis-material-advanced: 1.7.3
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_translations_js.395fc3f6.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-gauges/static/js/src_translations_js.cace16e5.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_translations_js.0b5e71d6.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/css/src_Map_jsx-node_modules_leaflet_dist_leaflet_css-node_modules_babel_runtime_helpers_esm_obje-1f1968.c7bfc0ae.chunk.css.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/css/src_RGBLight_jsx-node_modules_babel_runtime_helpers_esm_extends_js-node_modules_babel_runtime-b72c90.3aa647cd.chunk.css.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Thermostat_jsx.9fe80f2d.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Generic_jsx-src_ObjectChart_jsx.b796934b.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/css/src_JaegerDesignCameras_jsx.20077502.chunk.css.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/css/src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_exte-89999d.20077502.chunk.css.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/css/src_JaegerDesignDimmer_jsx.20077502.chunk.css.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Actual_jsx-node_modules_babel_runtime_helpers_esm_setPrototypeOf_js.70ad77f0.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Lock_jsx.40dd2216.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Components_BlindsBase_js.a97ca885.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Components_DoorAnimation_js-src_Components_LockAnimation_js.05f2a81b.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Blinds_jsx-src_Generic_jsx.aff9b982.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Switches_jsx.846eb8e0.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/css/src_JaegerDesignState_jsx.20077502.chunk.css.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/css/src_JaegerDesignNews_jsx-node_modules_babel_runtime_helpers_classCallCheck_js-node_modules_ba-5ed22c.20077502.chunk.css.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/css/src_JaegerDesignShutter_jsx.20077502.chunk.css.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/css/src_JaegerDesignScene_jsx-src_css_montserrat_css.20077502.chunk.css.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/css/src_JaegerDesignPlayer_jsx.20077502.chunk.css.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Clock_jsx.a7c0e64d.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/css/src_JaegerDesignThermostat_jsx-src_css_montserrat_css.20077502.chunk.css.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_RGBLight_jsx-node_modules_babel_runtime_helpers_esm_extends_js-node_modules_babel_runtime-b72c90.74bca79b.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_SimpleState_jsx.ecde697f.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_ViewInWidget_jsx.47d8f677.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Security_jsx.1b52604e.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Camera_jsx.32981db1.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Player_jsx.d3deecb7.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Html_jsx.53c58f1e.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_ThemeSwitcher_jsx.43aeca65.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_WasherDryer_jsx.765e8e3e.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Wizard_jsx.a824b7b9.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_deviceWidget_js.5b77c3f1.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-gauges/static/js/src_WaterGauge_jsx.55c65fc6.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-gauges/static/js/src_ColorGauge_jsx-node_modules_babel_runtime_helpers_esm_defineProperty_js-node_modules_babe-17d7ec.7cfe7aba.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerButton_jsx-src_JaegerDialog_jsx.d3af1903.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-gauges/static/js/src_BatteryGauge_jsx.9a9b6397.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerSettings_jsx-src_icons_MenuIcon_jsx-src_icons_ScenesIcon_jsx.255b156b.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerDesignLayout_jsx-src_css_montserrat_css-node_modules_babel_runtime_helpers_esm_exte-89999d.416145c6.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
instrument.ts:144 Translate: jqui_html_dialog
instrument.ts:144 Translate: jqui_icon_dialog
instrument.ts:144 Translate: jqui_container_dialog
instrument.ts:144 Translate: tabs
instrument.ts:144 Translate: colorpicker
instrument.ts:144 Translate: dwd
instrument.ts:144 Translate: echarts
instrument.ts:144 Translate: info
instrument.ts:144 Translate: jqplot
instrument.ts:144 Translate: metro
instrument.ts:144 Translate: swipe
instrument.ts:144 Translate: trashschedule
instrument.ts:144 Translate: vis-inventwo
instrument.ts:144 Translate: vis-material-advanced
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerDesignCameras_jsx.95603807.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerDesignDimmer_jsx.cada2879.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerDesignNews_jsx-node_modules_babel_runtime_helpers_classCallCheck_js-node_modules_ba-5ed22c.369ad0ed.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerDesignScene_jsx-src_css_montserrat_css.e905496e.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerDesignPlayer_jsx.2127eab0.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerDesignShutter_jsx.edd2cd05.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerDesignState_jsx.d5618f8c.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.57:8082/vis-2/widgets/vis-2-widgets-jaeger-design/static/js/src_JaegerDesignThermostat_jsx-src_css_montserrat_css.aead2071.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
instrument.ts:144 Common user CSS not found: Not exists
(anonym) @ instrument.ts:144
(anonym) @ visEngine.jsx:1911
Promise.catch (async)
value @ visEngine.jsx:1911
value @ visEngine.jsx:1949
ji @ react-dom.production.min.js:204
Li @ react-dom.production.min.js:203
Cs @ react-dom.production.min.js:292
Hl @ react-dom.production.min.js:280
gl @ react-dom.production.min.js:280
zl @ react-dom.production.min.js:280
ol @ react-dom.production.min.js:268
V @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
e5eac493-04c4-4972-badf-8d408882c06d:1 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://192.168.178.57:8082/lib/js/ace/worker-json.js' failed to load.
    at blob:http://192.168.178.57:8082/e5eac493-04c4-4972-badf-8d408882c06d:1:1
(anonym) @ e5eac493-04c4-4972-badf-8d408882c06d:1
helpers.ts:120 Uncaught TypeError: i.forEach is not a function
    at WidgetImportDialog.jsx:33:17
    at Object.action (WidgetImportDialog.jsx:75:13)
    at onClick (IODialog.jsx:39:27)
    at Object.At (react-dom.production.min.js:54:317)
    at _t (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Fr (react-dom.production.min.js:105:68)
    at Er (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at hl (react-dom.production.min.js:274:42)
    at Zt (react-dom.production.min.js:52:375)
    at Wr (react-dom.production.min.js:109:469)
    at Ge (react-dom.production.min.js:74:59)
    at $e (react-dom.production.min.js:73:73)
    at HTMLBodyElement.i (helpers.ts:98:1)
(anonym) @ WidgetImportDialog.jsx:33
action @ WidgetImportDialog.jsx:75
onClick @ IODialog.jsx:39
At @ react-dom.production.min.js:54
_t @ react-dom.production.min.js:54
(anonym) @ react-dom.production.min.js:55
Fr @ react-dom.production.min.js:105
Er @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
hl @ react-dom.production.min.js:274
Zt @ react-dom.production.min.js:52
Wr @ react-dom.production.min.js:109
Ge @ react-dom.production.min.js:74
$e @ react-dom.production.min.js:73
i @ helpers.ts:98
````

**Versions:**  
 - Adapter version: 2.2.7
 - JS-Controller version: 5.0.12
 - Node version: 18.17.0
 - Operating system: Rapsberry bullseye
 - Browser: Chrome

**Additional context**

**Comment by PiemurIsBack** [comment]
Hat sich erledigt, das zu importierende Widget war wohl kaputt bzw. notwendige Adapter war nicht installiert
